version: '3.8'

services:
  app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/synthetic_data_db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=synthetic_data_db
    ports:
      - "5433:5432"  # Expose port 5432 of the container on port 5433 of the host
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
