version: '3'

services:
  app:
    build: .
    container_name: synthetic_data_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/synthetic_data_db

  db:
    image: postgres:14
    container_name: synthetic_data_db
    environment:
      POSTGRES_DB: synthetic_data_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
